### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by p4nix** [klieret/AnkiPandas#36] opened 2020-06-25 07:39 UTC
I am not very experienced with Python, but I tried getting a basic example to work and it fails:

```
INFO: Searching for database. This might take some time. You can speed this up by specifying a search path or directly entering the path to your database.
WARNING: The search will stop at the first hit, so please verify that the result is correct (for example in case there might be morethan one Anki installations)
INFO: Loaded db from /Users/XXXX/Library/Application Support/Anki2/XXXX/collection.anki2
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    cards = col.cards.merge_notes()
  File "/usr/local/lib/python3.7/site-packages/ankipandas/collection.py", line 99, in cards
    return self._get_item("cards")
  File "/usr/local/lib/python3.7/site-packages/ankipandas/collection.py", line 83, in _get_item
    r = self._get_original_item(item).copy(True)
  File "/usr/local/lib/python3.7/site-packages/ankipandas/collection.py", line 76, in _get_original_item
    r = AnkiDataFrame.init_with_table(self, item)
  File "/usr/local/lib/python3.7/site-packages/ankipandas/ankidf.py", line 103, in init_with_table
    new._get_table(col, table, empty=empty)
  File "/usr/local/lib/python3.7/site-packages/ankipandas/ankidf.py", line 98, in _get_table
    self.normalize(inplace=True)
  File "/usr/local/lib/python3.7/site-packages/ankipandas/ankidf.py", line 1025, in normalize
    self["cdeck"] = self["did"].map(raw.get_did2deck(self.db))
  File "/usr/local/lib/python3.7/site-packages/ankipandas/raw.py", line 294, in get_did2deck
    dinfo = get_deck_info(db)
  File "/usr/local/lib/python3.7/site-packages/ankipandas/raw.py", line 281, in get_deck_info
    return get_info(db)["decks"]
  File "/usr/local/lib/python3.7/site-packages/ankipandas/raw.py", line 120, in get_info
    ret[col] = json.loads(val)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.de
coder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The code is:

```python
from ankipandas import Collection
col = Collection()

cards = col.cards.merge_notes()
selection = cards[cards.has_tag("leech")]
selection["cdeck"].value_counts().plot.pie()
```

Is there anything I am doing wrong? I tested both on Anki 2.1.26 and .28alpha3, running on macOS. Python version 3.7.

**Comment by klieret** [comment] 2020-06-25 08:29
Hi,

thanks for reporting this! It looks like you did everything wrong, so this seems to be a bug. I'll take a look later at what might cause this.

Cheers,
Kilian

**Comment by p4nix** [comment] 2020-06-25 10:49
Hi,

thanks for looking into this. You can take your time, as analysing my repetition data would have been procrastination for more important matters anyway ;)

If you need any additional informations for reproducing the error, etc. just let me know!

Cheers,
p4nix

**Comment by p4nix** [comment] 2020-07-03 09:39
@klieret This error most likely has to do with the changes introduced by the Anki 2.1.26/2.1.28beta. I have just tried a minimal example with a collection made with Anki 2.1.23, which actually worked. As I did actually downgrade my Anki 2.1.28 collection to .26, I was confused whether or not this was the real error, but it seems that ankipandas does not support .26 collections as well. But again, .23 works without any issues!

(inspiration gotten from: https://forums.ankiweb.net/t/json-decoder-jsondecodeerror-expecting-value-line-1-column-1-char-0/622)

**Comment by klieret** [comment] 2020-07-09 13:39
@p4nix  Sorry for not replying earlier, not much time at my hands recently! I'd be very happy if we could work out why this is happening. I'll push a new version that includes some debug statements that should get triggered if such an error occurs and hopefully will tell us more about the source of the problem!   Would you be willing to test with the new version as well?  That would be awesome!

**Comment by klieret** [comment] 2020-07-09 13:41
Actually it could also simply be that there's an empty string in the database:
```python
import json
json.loads("")
```
results in
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

In that case the problem would be trivial to solve

**Comment by klieret** [comment] 2020-07-09 13:56
Hi @p4nix I just made a new release from this.

Could you do
```
pip3 install --upgrade ankipandas
```
Then you should have ``ankipandas`` version 0.3.4. If we're lucky the problem is solved now, if not at least we get more insight from the error messages!

Let me know if this solves the issue and thank you again for putting in the time to experiment and help me solve this :)

**Comment by klieret** [comment] 2020-07-09 13:58
> thanks for reporting this! It looks like you did everything wrong, so this seems to be a bug. 

You did everything right of course! Sorry about this typo! And you also provided all the information to fix this, I really couldn't ask for more!

**Comment by p4nix** [comment] 2020-07-09 14:12
I tested a small example, and it did work! Thanks for fixing it. I will do some more tests as soon as time permits to make sure that everything is working okay, but I did get a simple histogram to render :) Thanks!

**Comment by klieret** [comment] 2020-07-09 18:11
Cool! I'll close this for now, but feel free to reopen it if anything doesn't work!   

> I will do some more tests as soon as time permits to make sure that everything is working okay

Awesome!

**Closed by klieret** 2020-07-09 18:11 UTC
Labels: bug

**Comment by klieret** [comment] 2020-11-28 15:33
@allcontributors please add @p4nix for bug
